import os
from ..bridge.utils import _get_codex_config_dir, _safe_write_text


def write_config(final_models, top_n=None):
    codex_dir = _get_codex_config_dir()
    config_toml_path = os.path.join(codex_dir, "config.toml")
    first_model = final_models[0]["label"] if final_models else ""
    toml_lines = [
        f'# Generated by g4f-bridge',
        f'model = "{first_model}"',
        f'model_provider = "g4f-bridge"',
        f'',
        f'[model_providers.g4f-bridge]',
        f'name = "G4F/EAON Bridge"',
        f'base_url = "http://127.0.0.1:1337/v1"',
        f'wire_api = "responses"',
        f'env_key = "BRIDGE_API_KEY"',
        f'',
    ]
    ok, err = _safe_write_text(config_toml_path, "\n".join(toml_lines))
    if ok:
        print(f"Codex CLI: {config_toml_path} successfully updated!")
        if not os.environ.get("BRIDGE_API_KEY"):
            print(f"  BRIDGE_API_KEY not set! Run: export BRIDGE_API_KEY=dummy_key")
        print(f"  {len(final_models)} models available. Use: codex --model \"{first_model}\"")
    else:
        print(f"Codex CLI: Failed to write config: {err}")
